# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Bank The Nifty
email: bankthenifty@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, Bank The Nifty is a blog based on a data analysis of Nitfy 50 closing prices for the past 20 years ranging till Feb 26 2020.
  I have calculated percentage changes weekly, monthly, daily, friday to thursday, monday to thursday, wednesday to thursday and friday to thursday.
  This can help us to make better option expiry calls and puts writing.
  This is by no means an exhaustive study, so be careful if you use the results for trading
  I blog about summaries of the study, my weekly options trading results based on the study and ideas which I plan to pursue in the coming expiry week/month
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: royce2892
# Build settings
theme: minima
#remote_theme: mmistakes/minimal-mistakes@4.22.0
plugins:
  - jekyll-feed

---
layout: default
comments: true
disqus:
  shortname: bankthenifty
# other options
---

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
